//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepperPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string ClassId { get; set; }
        public string Name { get; set; }
        public string Prerequisites { get; set; }
        public string GesSatisfied { get; set; }
        public string MajorSatisfied { get; set; }
        public string MinorSatisfied { get; set; }
        public Nullable<int> Units { get; set; }
        public string SemestersOffered { get; set; }
    }
}
